Feat/status filter on send bag
eCOO-FURG/apps pull request #138
Opened 2024-10-14 23:04 UTC by zelindro

📝 Nome da issue
[CDD] - Desenvolver um filtro de informação para os novos status de envio.

🚀 O que foi feito?
Foram implementados botões que possibilitam a filtragem das sacolas presentes em "Enviar Sacola" baseado em seus status. Além disso foi implementado o nome da farm na tela de "Montar Sacola" como está no figma.

📷 Visualização
![image](https://github.com/user-attachments/assets/6ccc0e80-4912-4c97-8d81-6916687ec308)
![image](https://github.com/user-attachments/assets/4d9f1cfc-19fc-4063-ba8e-f7c97d110a03)
![image](https://github.com/user-attachments/assets/a8c763af-f4db-4ba9-a76d-f36abb11cb1f)
![image](https://github.com/user-attachments/assets/35c6e430-f526-4739-88fb-0db1b53df63c)

2024-10-15 00:47 UTC, ilucaslima requested changes

2024-10-15 00:47 UTC, ilucaslima commented on cdd/src/app/(protected)/(footered)/enviar-sacola/components/table.tsx
> +    <table className="bg-white text-theme-primary leading-7 w-full table-fixed rounded-lg mt-3 mb-auto">
Esse table já existe em: cdd/src/app/(protected)/(footered)/ofertas/[box_id]/components/page.tsx
use o componente existente

2024-10-15 00:47 UTC, ilucaslima commented on cdd/src/app/(protected)/(footered)/montar-sacola/[bag_id]/components/BagMiniTable.tsx
> +            <div className="flex gap-8 items-start text-theme-primary border-b-[1px] border-theme-background p-3">
border-b-[1px] é o mesmo que border-b, válida se é realmente verdade e ajusta pra tirar o personalizado.

2024-10-15 14:08 UTC, zelindro commented on cdd/src/app/(protected)/(footered)/enviar-sacola/components/SendBagTable.tsx
> +  const [selectedStatus, setSelectedStatus] = useState("ALL");
Certo, daqui para frente quando ver algo que já existe ou for começar algo já vou componentizar. Nesse caso aqui não imagino que esse modelo vai ser usado em mais nenhum lugar fora esses dois, então vou deixar como está.

2024-10-16 12:36 UTC, ilucaslima requested changes
Foi solicitado algumas alterações no code review anterior que não foram feitas, é necessário corrigir para que a gente suba esse código padronizado com o projeto.
Mudanças essas: Validação de função, componentização e melhorias no typescript.

2024-10-21 19:20 UTC, zelindro commented
📝 Nome da issue
[Produtor] - Trocar o Nome da campo de cadastro do negócio;
[Produtor] - Adicionar um loader no componente de etapa atual ciclo;
[CDD] - Descrição dos itens em "Montar" e "Enviar" sacola.

🚀 O que foi feito?
Foram feitas todas as demandas presentes em cada card no Clickup, sendo essas, agrupar itens na descrição de um pedido (na tela de montar e enviar sacolas), foi implementado também o nome da farm responsável pela venda de um determinado produto, foi adicionado um loader no componente de etapa atual do ciclo (removendo assim o componente placeholder e por fim o CAF foi substituído por Talão na tela de cadastro do produtor bem como o termo agronegócio foi mudado para Agroprodução Familiar.

2024-10-24 04:21 UTC, LucasMachadoG requested changes
Fazer um rebase com a develop para resolver os conflitos

2024-10-27 22:35 UTC, LucasMachadoG requested changes

2024-11-07 03:54 UTC, LucasMachadoG approved these changes

2024-11-07 05:10 UTC, merged