Refactor/modelpage forgot password
eCOO-FURG/apps pull request #147
Opened 2024-10-26 12:33 UTC by ilucaslima

[x] - Foi refatorado a tela de esqueci senha para uso do ModelPage
[x] - Foi refatorado o bottonv2 removendo os valores personalizados do component

2024-10-26 21:46 UTC, LucasMachadoG requested changes

2024-10-26 21:46 UTC, LucasMachadoG commented on producer/src/app/(protected)/(footered)/recuperar-senha/page.tsx
> +          <Input
Como comentei contigo no wpp, eu tinha criado um input novo. CustomInput, ele já está praticamente igual ao figma, única coisa que vi que ta um pouco diferente é a questão do px, hoje ele esta com px-4, mas o certo seria px-3, ai se quiser já mudar. Ele tambem pode receber erros vindo formulário caso tu queira

2024-10-26 21:46 UTC, LucasMachadoG commented on producer/src/app/(protected)/(footered)/recuperar-senha/page.tsx
> +    <ModelPage
Acho que ficaria melhor se colocassemos um pt no nosso modelPage, tinha dado uma testada e ficaria legal um pt-16, deixando um pouco mais parecido com o figma

    <ModelPage
      titleClassName='pt-16'
      title="Esqueci a senha"
      subtitle="Enviaremos um código de verificação para o email abaixo"
      overflowAuto={true}
    >

2024-10-26 21:46 UTC, LucasMachadoG commented on producer/tailwind.config.ts
Se conseguir remover o tailwind.config, o gabriel tinha subido aquela alteração do gitignore, para n ter que ficar removendo ele toda vez que iremos subir algo. Eu fiz um hotfix na develop, apenas removendo esse arquivo do repositorio, agora ele n vai mais ser pego na hora de subir algo

2024-10-27 02:35 UTC, ilucaslima commented on producer/src/app/(protected)/(footered)/recuperar-senha/page.tsx
> +    <ModelPage
Pra seguir o figma é necessário inserir um pouco mais do que 'pt-16', seria aproximadamente 'pt-28'.
Melhor do que inserir um valor pra distanciar o título da "parede" superior, é a gente trazer uma abordagem de alinhamento centralizado. Vou trazer essa proposta pra o Marcelo e nosso design Teixeira, tendo uma aprovação a gente conversa pra inserir no model page.

2024-10-28 14:48 UTC, LucasMachadoG approved these changes

2024-10-28 14:52 UTC, merged