Feat/handle producers
eCOO-FURG/apps pull request #174
Opened 2024-11-26 12:22 UTC by zelindro

Esse é o PR referente a seguinte task ["[App Admin] - Controle de Produtores"](https://app.clickup.com/t/86a5bxc1q)

O que foi feito?

- Foi desenvolvida e integrada a tela de alteração de status dos produtores para aprovado/rejeitado, foi implementada a tabela dos produtores no mesmo modelo do componente OrderTable que já vinhamos usando.

2024-11-28 23:51 UTC, gabrieltjaeger requested changes
Falta o padding inferior da página e também falta o logo, informações de direitos autorais e os gráficos mesmo que com dados mockados.

![image](https://github.com/user-attachments/assets/c1e36575-45ea-4a58-a4c6-76fe517701f2)

![image](https://github.com/user-attachments/assets/753bc39d-2d31-44e8-8c97-3e6801d0f7b3)

Precisa ajustar algumas coisas e há muita repetição de código. Seria interessante pensar em soluções alternativas para reduzir a repetição.

Será necessário refatorar toda a home page para implementar os dados reais quando as rotas do backend estiverem prontas.

2024-11-28 23:51 UTC, gabrieltjaeger commented on admin/src/_actions/farm/get-farms.ts
Usar o padrão de criação de interfaces proposto na descrição do seguinte PR:
https://github.com/eCOO-FURG/apps/pull/169

O nome da action deve ser o mesmo nome do controller da rota que está sendo consumida. Ademais, o caminho deveria ser `/_actions/farms (plural)/GET (nome do método chamado)/list-farms.ts`, ficando:
```
admin/src/_actions/farms/GET/list-farms.ts
```

Essa action não será usada no APP do agente do CDD? Se sim, mover para o /shared. Se não, pode manter no /admin.

O nome da interface do request deve refletir o nome do controller, bem como o nome da action.

### Interface:
```typescript
interface ListFarmsRequest {}
```

### Função:
```typescript
export async function listFarms({ 
  page,
  farm = "",
}: ListFarmsRequest) {}
```

2024-11-28 23:51 UTC, gabrieltjaeger commented on admin/src/_actions/farm/patch-farms.ts
Usar o padrão de criação de interfaces proposto na descrição do seguinte PR:
https://github.com/eCOO-FURG/apps/pull/169

O nome da action deve ser o mesmo nome do controller da rota que está sendo consumida. Ademais, o caminho deveria ser `/_actions/farms (plural)/PATCH (nome do método chamado)/handle-farm-status.ts`, ficando:
```
admin/src/_actions/farms/PATCH/handle-farm-status.ts
```

O nome da interface do request deve refletir o nome do controller, bem como o nome da action.

### Interface:
```typescript
interface HandleFarmStatusRequest {}
```

### Função:
```typescript
export async function handleFarmStatus({ 
  farm_id,
  status,
}: HandleFarmStatusRequest) {}
```

2024-11-28 23:51 UTC, gabrieltjaeger commented on admin/src/app/components/LastSalesTable.tsx
> +      <div className="w-full max-h-[415px] overflow-y-auto scrollbar-thin scrollbar-thumb-gray-300 scrollbar-track-gray-100">
Não utilizar valores personalizados como `max-h-[415px]`. Se necessário usar esse valor, configurar tamanho personalizado em `spacing` no `/shared/tailwind.config.ts`. Também evitar o uso da unidade px em favor da unidade rem. No caso do design das nossas aplicações, está definido que `1rem ≡ 16px`.

2024-11-28 23:51 UTC, gabrieltjaeger commented on admin/src/app/components/ProducerTable.tsx
> +          className="flex flex-col w-[28%] h-[54%]"
Não utilizar valores personalizados `w-[28%] h-[54%]`. É necessário definir as dimensões do modal com class name? Isso poderia ser definido dentro do próprio componente configurado para ser responsivo https://tailwindcss.com/docs/responsive-design

2024-11-28 23:51 UTC, gabrieltjaeger commented on admin/src/app/components/ProducerTable.tsx
> +          </div>
Repetição de código. Poderia usar map.

2024-11-28 23:51 UTC, gabrieltjaeger commented on admin/src/app/components/ProducerTable.tsx
> +              } text-white justify-center items-center w-25 h-9 text-sm font-semibold rounded-full`}
Não utilizar condições ternárias, menos ainda ternários dentro de ternários. Dificulta a leitura. Poderia criar uma função para retornar a classe de acordo com o status, como é feito em algumas funções em /utils.

### Exemplo em `/shared/src/utils/convert-unit`:
```typescript
export const convertUnit = (type: string) => {
  const types: Record<string, string> = {
    UNIT: "un.",
    WEIGHT: "kg",
  };

  return types[type];
};
```

2024-11-28 23:51 UTC, gabrieltjaeger commented on admin/src/app/layout.tsx
> +            <div className="w-full h-full p-15">{children}</div>
Por que trocou o elemento `main` por `div`? Idealmente devemos usar elementos descritivos e semânticos, o que melhora o SEO e também a fluidez da leitura do código.

2024-11-28 23:51 UTC, gabrieltjaeger commented on admin/src/app/page.tsx
Não é aconselhável que uma página possua mais de um elemento `<h1>`, o que pode ser permitido em alguns contextos específicos, como dentro de uma `<section>`, podendo haver mais de uma na página. Por isso, use `<h1>` apenas quando necessário, pois ele é o título mais importante no seu contexto. Para subtítulos ou hierarquias menores, usar `<h2>`, `<h3>` e assim por diante.

Seria interessante usar tags `<section>` no lugar das `<div>` nessa página para separar os diferentes espaços da página _home_ do app do admin de forma mais semântica, o que também permitiria o uso das tags `<h1>` no contexto da seção.

2024-11-28 23:51 UTC, gabrieltjaeger commented on admin/src/app/components/ProducerTable.tsx
> +import { IProducer } from "@shared/interfaces/user";
Interfaces com o prefixo I não serão mais utilizadas após o merge do PR #169. Será necessário atualizar quando ele for aprovado.

2024-11-28 23:51 UTC, gabrieltjaeger commented on admin/src/app/produtores/page.tsx
> +import IProducerTable from "../components/ProducerTable";
Interfaces com o prefixo I não serão mais utilizadas após o merge do PR #169. Será necessário atualizar quando ele for aprovado.

2024-11-28 23:51 UTC, gabrieltjaeger commented on admin/src/app/produtores/page.tsx
> +import { IProducer } from "@shared/interfaces/user";
Interfaces com o prefixo I não serão mais utilizadas após o merge do PR #169. Será necessário atualizar quando ele for aprovado.

2024-11-28 23:51 UTC, gabrieltjaeger commented on shared/src/interfaces/user.ts
Interfaces com o prefixo I não serão mais utilizadas após o merge do PR https://github.com/eCOO-FURG/apps/pull/169. Será necessário atualizar quando ele for aprovado.

2024-11-28 23:51 UTC, gabrieltjaeger commented on shared/src/interfaces/user.ts
> +import { StaticImageData } from 'next/image';
O que é esse StaticImageData?

2024-11-28 23:51 UTC, gabrieltjaeger commented on shared/src/components/ModalV2.tsx
> +interface IModalV2Props {
Interfaces que definem as props de um componente devem seguir o estilo:
```typescript
interface NomeComponenteProps {}
```

2024-12-02 17:07 UTC, zelindro commented on shared/src/interfaces/user.ts
> +import { StaticImageData } from 'next/image';
Foi uma tipo de dado que eu puxei do next/image ali para poder tipar o dado da imagem vinda do banco. Mas depois do seu comentário aqui chequei lá e vi que está como string, então vou alterar aqui.

2024-12-02 17:10 UTC, zelindro commented
> 

Vou deixar para fazer as alterações da home na própria branch dela, eu acabei criando essa aqui a partir da branch do Lima do modal que ele fez em cima da branch da home, aí ficou uma bagunça por que ainda estou esperando a rota dos gráficos do Machado para terminar a Home. Dito isso, vou voltar essa home aqui para a versão em branco e aí eu subo a home nova com essas alterações que comentasse na própria branch dela.

2024-12-02 17:17 UTC, zelindro commented on admin/src/app/components/ProducerTable.tsx
> +          className="flex flex-col w-[28%] h-[54%]"
Eu defini no className por que esse componente foi criado pelo Lima para ser o modal no admin mas ele não encaixava 100% no modal dessa tela, visto que no figma ali ele é um pouco menor, aí coloquei personalizado. Depois de olhar novamente não achei que ficou ruim deixar na mesma altura e largura que o Lima fez para a outra tela, então vou remover e deixar do tamanho default que ele definiu.

2024-12-02 19:46 UTC, closed without merging